.windows_build_template: &windows_build_definition
  stage: build
  variables:
    C2_ENABLE_LTO: $FORCE_LTO
    C2_ENABLE_CRASHPAD: $SKIP_CRASHPAD == "false"
  before_script:
    - echo "Installing Conan..."
    - pip install --upgrade conan
    - conan --version
    - conan profile detect -f
  script:
    - echo "Building on Windows..."
    - mkdir build
    - cd build
    - conan install ..
        -s build_type=RelWithDebInfo
        -c tools.cmake.cmaketoolchain:generator="NMake Makefiles"
        -b missing
        --output-folder=.
        -o with_openssl3="True"
    - cmake
        -G"NMake Makefiles"
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
        -DUSE_PRECOMPILED_HEADERS=ON
        -DBUILD_WITH_CRASHPAD="$C2_ENABLE_CRASHPAD"
        -DCHATTERINO_LTO="$C2_ENABLE_LTO"
        -DFORCE_JSON_GENERATION=On
        ..
    - $env:cl = "/MP"
    - nmake /S /NOLOGO
    - |
      if [ "$SKIP_CRASHPAD" == "false" ]; then
        nmake /S /NOLOGO bajerino-crash-handler
        mkdir Bajerino2/crashpad
        cp bin/crashpad/crashpad-handler.exe Bajerino2/crashpad/crashpad-handler.exe
        7z a bin/bajerino-Qt-${QT_VERSION}.pdb.7z bin/bajerino.pdb
      fi
    - windeployqt bin/bajerino.exe --release --no-compiler-runtime --no-translations --no-opengl-sw --dir Bajerino2/
    - cp bin/bajerino.exe Bajerino2/
    - .CI/deploy-crt.ps1 Bajerino2
    - echo nightly > Bajerino2/modes
    - 7z a bajerino-windows-x86-64-Qt-${QT_VERSION}.zip Bajerino2/
  artifacts:
    paths:
      - "build/bajerino-windows-x86-64-Qt-${QT_VERSION}.zip"
      - "build/bin/bajerino-Qt-${QT_VERSION}.pdb.7z"
    expire_in: 7 days
  tags:
    - saas-windows-medium-amd64

build-windows:
  extends: .windows_build_template
  variables:
    QT_VERSION: "6.7.1"
    FORCE_LTO: "false"
    SKIP_CRASHPAD: "false"
    RUNNER_OS: "windows"
